# Generated by Django 2.2.4 on 2020-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTAble',
            fields=[
                ('prd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prd_name', models.CharField(max_length=30)),
                ('prd_quntity', models.CharField(max_length=20)),
                ('prd_price', models.IntegerField()),
                ('prd_manf_dt', models.DateField()),
                ('prd_exp_dt', models.DateField()),
            ],
        ),
    ]
