# Generated by Django 2.2.4 on 2020-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='prd_price',
            field=models.IntegerField(default=False),
        ),
    ]
